### ISSUE TITLE
Snowstorm not honoring --exit flag when loading SNOMED CT

### ISSUE THREAD

**Issue by fadam-mm** [IHTSDO/snowstorm#167]
When deploying snowstorm and doing the initial load with the `--exit` flag, the process does not exit after the load is complete.

```
2020-09-25 17:44:44.325  INFO 7724 --- [main] o.s.s.core.rf2.rf2import.ImportService   : Completed RF2 SNAPSHOT import on branch MAIN in 1417 seconds. ID bad6aefd-bf9a-4e24-ae30-d574ec6eb8d1
2020-09-25 17:44:44.333  INFO 7724 --- [main] o.snomed.snowstorm.SnowstormApplication  : Exiting application.
2020-09-25 17:44:44.333  INFO 7724 --- [main] ConfigServletWebServerApplicationContext : Closing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@61443d8f: startup date [Fri Sep 25 17:20:52 UTC 2020]; root of context hierarchy
2020-09-25 17:44:44.336  INFO 7724 --- [main] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 2147483647
2020-09-25 17:44:44.337  INFO 7724 --- [main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2020-09-25 17:44:44.535  INFO 7724 --- [classification-status-polling] o.s.s.c.d.s.c.ClassificationService      : Classification status polling thread stopped.
```

The app hangs and waits at this point and does not exit. We've observed similar behavior when snowstorm starts up before elasticsearch and it appeared to hang due to a background thread polling every 10 seconds (related to `IdentifierCacheManager`). 

The expectation is with the `--exit` flag, snowstorm should shutdown the background thread and exit the process. If we manually stop the process and restart everything, it works fine. However, this is impacting our deployment which runs in an environment with no logins.

openjdk version "1.8.0_265"
Snowstorm version:  4.12.1
Elasticsearch: 6.8.0

Thanks in advance for the support!

**Comment by kaicode** [comment]
Thank you for raising this! We'll look into it.

**Comment by kaicode** [comment]
This issue is fixed in the develop branch and will be included in the next Snowstorm release.

**Comment by kaicode** [comment]
Fixed in [5.0.6](https://github.com/IHTSDO/snowstorm/releases/tag/5.0.6).

**Comment by fadam-mm** [comment]
Thanks for the quick turnaround! 

We tested again this week. `--exit` is working better when things start up correctly. But snowstorm is still not exiting if elasticsearch hasn't started yet. The error is different compared to before. Pre-5.0.6 it would hang and appeared to continue to poll, now the stack looks like:

```
2020-10-21 09:26:36.820  INFO 3283 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Topping up IdCache(0 - 01) by 2000
2020-10-21 09:26:36.832  WARN 3283 --- [           main] .d.e.r.s.AbstractElasticsearchRepository : Cannot create index: Connection refused; nested exception is java.lang.RuntimeException: Connection refused
2020-10-21 09:26:36.972 ERROR 3283 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Failed to top-up IdCache(0 - 01) with 2000 identifiers 

org.springframework.dao.DataAccessResourceFailureException: Connection refused; nested exception is java.lang.RuntimeException: Connection refused
	at org.springframework.data.elasticsearch.core.ElasticsearchExceptionTranslator.translateExceptionIfPossible(ElasticsearchExceptionTranslator.java:76)
	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.translateException(ElasticsearchRestTemplate.java:398)
	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.execute(ElasticsearchRestTemplate.java:381)
	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.search(ElasticsearchRestTemplate.java:289)
	at org.springframework.data.elasticsearch.core.AbstractElasticsearchTemplate.search(AbstractElasticsearchTemplate.java:331)
	at org.snomed.snowstorm.core.data.services.identifier.LocalRandomIdentifierSource.findExistingIdentifiersInAnyBranch(LocalRandomIdentifierSource.java:83)
	at org.snomed.snowstorm.core.data.services.identifier.LocalRandomIdentifierSource.reserveIds(LocalRandomIdentifierSource.java:61)
	at org.snomed.snowstorm.core.data.services.identifier.IdentifierCacheManager.topUp(IdentifierCacheManager.java:118)
	at org.snomed.snowstorm.core.data.services.identifier.IdentifierCacheManager.checkTopUpRequired(IdentifierCacheManager.java:101)
	at org.snomed.snowstorm.core.data.services.identifier.IdentifierCacheManager.run(IdentifierCacheManager.java:66)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Connection refused
	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.translateException(ElasticsearchRestTemplate.java:396)
	... 9 common frames omitted
Caused by: java.net.ConnectException: Connection refused
	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:823)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:248)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:235)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1609)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1579)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1549)
	at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1065)
	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.lambda$search$11(ElasticsearchRestTemplate.java:289)
	at org.springframework.data.elasticsearch.core.ElasticsearchRestTemplate.execute(ElasticsearchRestTemplate.java:379)
	... 8 common frames omitted
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:174)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:148)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
	... 1 common frames omitted

2020-10-21 09:26:36.972  INFO 3283 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Topping up IdCache(0 - 02) by 4000
2020-10-21 09:26:36.984 ERROR 3283 --- [heManagerDaemon] o.s.s.c.d.s.i.IdentifierCacheManager     : Failed to top-up IdCache(0 - 02) with 4000 identifiers 
```

Is there any way we can have the process exit in this case, or perhaps configure it to exit after a number of failed retries to elasticsearch? Thanks again!

**Comment by kaicode** [comment]
Thanks for testing and coming back to us.
Yes, others have had a similar issue with Snowstorm only trying to connect to Elasticsearch once and the process not retrying or exiting if the connection fails. 
I would like to see Snowstorm attempt to connect to Elasticsearch for at least a minute (configurable) before giving up, at which point I agree that the process should exit. Thanks for raising this. I'll raise a separate issue for this.

**Comment by abdulmateenraj** [comment]
Hi, I ended up here by searching a similar error when trying to install Snowstorm (8.0 as well as 7.9.3). I am using Open JDK (Amazon Corretto 17) and Elastic Search version 7.7.0.


```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-08-03 09:16:37.615 ERROR 5320 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'FHIRStructureDefinitionProvider': Unsatisfied dependency expressed through field 'structureDefinitionRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'FHIRStructureDefinitionRepository' defined in org.snomed.snowstorm.fhir.repositories.FHIRStructureDefinitionRepository defined in @EnableElasticsearchRepositories declared on Config: Invocation of init method failed; nested exception is java.lang.reflect.InaccessibleObjectException: Unable to make field private java.lang.String java.util.TimeZone.ID accessible: module java.base does not "opens java.util" to unnamed module @5ae63ade
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1420)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at org.snomed.snowstorm.SnowstormApplication.main(SnowstormApplication.java:63)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:109)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'FHIRStructureDefinitionRepository' defined in org.snomed.snowstorm.fhir.repositories.FHIRStructureDefinitionRepository defined in @EnableElasticsearchRepositories declared on Config: Invocation of init method failed; nested exception is java.lang.reflect.InaccessibleObjectException: Unable to make field private java.lang.String java.util.TimeZone.ID accessible: module java.base does not "opens java.util" to unnamed module @5ae63ade
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1794)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1307)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1227)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
        ... 28 common frames omitted
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private java.lang.String java.util.TimeZone.ID accessible: module java.base does not "opens java.util" to unnamed module @5ae63ade
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at org.springframework.util.ReflectionUtils.makeAccessible(ReflectionUtils.java:782)
        at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:514)
        at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:705)
        at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:389)
        at java.base/java.util.Collections$SingletonSet.forEach(Collections.java:4905)
        at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:562)
        at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:520)
        at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:705)
        at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:389)
        at java.base/java.util.Collections$SingletonSet.forEach(Collections.java:4905)
        at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:562)
        at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:520)
        at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:705)
        at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:389)
        at java.base/java.util.Collections$SingletonSet.forEach(Collections.java:4905)
        at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:562)
        at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:520)
        at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:705)
        at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:389)
        at java.base/java.util.Collections$SingletonSet.forEach(Collections.java:4905)
        at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:562)
        at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:520)
        at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:705)
        at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:389)
        at java.base/java.util.Collections$SingletonSet.forEach(Collections.java:4905)
        at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.createAndRegisterProperty(AbstractMappingContext.java:562)
        at org.springframework.data.mapping.context.AbstractMappingContext$PersistentPropertyCreator.doWith(AbstractMappingContext.java:520)
        at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:705)
        at org.springframework.data.mapping.context.AbstractMappingContext.addPersistentEntity(AbstractMappingContext.java:389)
        at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:263)
        at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:206)
        at org.springframework.data.mapping.context.AbstractMappingContext.getPersistentEntity(AbstractMappingContext.java:90)
        at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$4(RepositoryFactoryBeanSupport.java:295)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:295)
        at org.springframework.data.elasticsearch.repository.support.ElasticsearchRepositoryFactoryBean.afterPropertiesSet(ElasticsearchRepositoryFactoryBean.java:69)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790)
        ... 38 common frames omitted

2022-08-03 09:16:37.631  INFO 5320 --- [-status-polling] o.s.s.c.d.s.c.ClassificationService      : Classification status polling thread stopped.
```
